# Cursor
cursor                  #ff9e64
cursor_text_color       #1a1b26
cursor_blink_interval   0

# Primary
foreground              #c0caf5
background              #1a1b26
selection_foreground    #1a1b26
selection_background    #ff9e64

# Normal
color0  #292e42
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #7aa2f7
color5  #bb9af7
color6  #7dcfff
color7  #c0caf5

# Bright
color8  #3b4261
color9  #f7768e
color10 #9ece6a
color11 #e0af68
color12 #7aa2f7
color13 #bb9af7
color14 #7dcfff
color15 #a9b1d6
